[platformio]
default_envs = heltec_v4
src_dir = esp32_marauder
boards_dir = boards

[env:heltec_v4]
platform = espressif32@6.12.0
framework = arduino
board = heltec_wifi_lora_32_v4
board_build.variants_dir = variants
board_build.partitions = heltec_android_16MB.csv
board_build.filesystem = spiffs
build_src_filter = +<*> -<libraries/>
monitor_speed = 115200
upload_speed = 115200
lib_ldf_mode = deep+
lib_extra_dirs = esp32_marauder/libraries
lib_deps =
  olikraus/U8g2@2.36.5
  https://github.com/marian-craciunescu/ESP32Ping.git#1.6
  ESP32Async/AsyncTCP@3.4.8
  ESP32Async/ESPAsyncWebServer@3.8.1
  stevemarple/MicroNMEA@2.0.6
  plerup/EspSoftwareSerial@8.1.0
build_flags =
  -D MARAUDER_HELTEC_V4
  -D HAS_VIRTUAL_SD
  -D ARDUINO_USB_MODE=1
  -D ARDUINO_USB_CDC_ON_BOOT=1
  -D CORE_DEBUG_LEVEL=1
  -D CONFIG_ASYNC_TCP_RUNNING_CORE=1
  -D ARDUINO_LOOP_STACK_SIZE=16384
  -Wl,-zmuldefs
  -fno-exceptions
